# Generated by Django 5.0.2 on 2024-02-21 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                ("thread_id", models.AutoField(primary_key=True, serialize=False)),
                ("creator", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewsComments",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("author_name", models.TextField()),
                ("creation_date", models.DateField()),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("info", models.TextField(default="", null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin")],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("profile_img", models.TextField(default="", null=True)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("news_id", models.AutoField(primary_key=True, serialize=False)),
                ("creation_date", models.DateField()),
                ("content_text", models.TextField()),
                ("content_img", models.TextField()),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("likes", models.IntegerField(default=0)),
                ("comments", models.ManyToManyField(default=[], to="api.newscomments")),
            ],
        ),
    ]
