# Generated by Django 5.0.1 on 2024-02-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                ("thread_id", models.IntegerField(primary_key=True, serialize=False)),
                ("creator", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
        ),
    ]
