# Generated by Django 5.0.1 on 2024-02-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                ("info_id", models.AutoField(primary_key=True, serialize=False)),
                ("project", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("news_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("content", models.TextField()),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="forum",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="forum",
            name="thread_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
