# Generated by Django 5.0.2 on 2024-02-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_sessions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="nickname",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="content_img",
            new_name="title",
        ),
        migrations.AddField(
            model_name="news",
            name="logo_img",
            field=models.ImageField(default="", upload_to="news_images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="news",
            name="main_img",
            field=models.ImageField(default=0, upload_to="news_images/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sessions",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
