# Generated by Django 5.0.1 on 2024-02-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="News_comments",
            new_name="NewsComments",
        ),
        migrations.RenameField(
            model_name="newscomments",
            old_name="authot_img",
            new_name="author_img",
        ),
    ]
