# Generated by Django 5.0.1 on 2024-02-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_news_comments_newscomments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.TextField(blank=True),
        ),
    ]
