# Generated by Django 4.2.6 on 2024-02-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_user_email_alter_user_nickname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hashs",
            field=models.BinaryField(default=b'', unique=True),
            preserve_default=False,
        ),
    ]
