# Generated by Django 5.0.1 on 2024-02-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_user_token_alter_user_info_alter_user_profile_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="token",
        ),
    ]
