# Generated by Django 5.0.1 on 2024-02-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="thread_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="news",
            name="news_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="newscomments",
            name="comment_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
