# Generated by Django 5.0.2 on 2024-02-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_rename_date_news_creation_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsComments",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("author_name", models.TextField()),
                ("author_img", models.TextField()),
                ("creation_date", models.DateField()),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("news_id", models.AutoField(primary_key=True, serialize=False)),
                ("creation_date", models.DateField()),
                ("content_text", models.TextField()),
                ("content_img", models.TextField()),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("likes", models.IntegerField(default=0)),
                ("comments", models.ManyToManyField(default=[], to="api.newscomments")),
            ],
        ),
    ]
