# Generated by Django 4.2.6 on 2024-03-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_user_email_alter_user_nickname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newscomments",
            name="content",
        ),
    ]
