# Generated by Django 4.2.6 on 2024-03-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_newscomments_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="newscomments",
            name="text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.TextField(default=""),
        ),
    ]
