# Generated by Django 4.2.6 on 2024-03-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_newscomments_text_alter_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="info",
            field=models.TextField(default="Your profile info here", null=True),
        ),
    ]
