import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Profile",
    description: "Generated by create next app",
    manifest: "/manifest.json",
    icons: {
      shortcut: { url: "/favicon.ico", type: "image/x-icon" },
      icon: [
        { url: "/favicon.ico", type: "image/x-icon" },
        { url: "/favicon.svg", type: "image/svg+xml" },
        { url: "/favicon-16x16.png", type: "image/png", sizes: "16x16" },
        { url: "/favicon-32x32.png", type: "image/png", sizes: "32x32" },
        {
          url: "/android-chrome-192x192.png",
          type: "image/png",
          sizes: "192x192",
        },
      ],
      apple: [
        { url: "/apple-touch-icon.png", sizes: "57x57", type: "image/png" },
      ],
    },
  }

const ProfileLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
  return (
    <>{children}</>
  )
}

export default ProfileLayout;